# Generated by Django 4.0.5 on 2022-07-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbooks', '0003_book_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.URLField()),
            ],
        ),
    ]
