# Generated by Django 4.0.5 on 2022-07-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbooks', '0004_userslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslink',
            name='links',
            field=models.CharField(max_length=100),
        ),
    ]
